parameters:
    ingenico.method.identifier_prefix.ingenico: 'ingenico'

services:
    Ingenico\Connect\OroCommerce\Form\Type\IngenicoSettingsType:
        arguments:
            - '@translator.default'
            - '@Ingenico\Connect\OroCommerce\Settings\DataProvider\PaymentActionDataProvider'
            - '@Ingenico\Connect\OroCommerce\Settings\DataProvider\EnabledProductsDataProvider'
        tags:
            - { name: form.type }

    Ingenico\Connect\OroCommerce\Integration\IngenicoChannel:
        tags:
            - { name: oro_integration.channel, type: '%ingenico.method.identifier_prefix.ingenico%' }

    Ingenico\Connect\OroCommerce\Integration\IngenicoTransport:
        tags:
            - { name: oro_integration.transport, type: '%ingenico.method.identifier_prefix.ingenico%', channel_type: ingenico }

    Ingenico\Connect\OroCommerce\Settings\DataProvider\PaymentActionDataProvider: ~

    Ingenico\Connect\OroCommerce\Settings\DataProvider\EnabledProductsDataProvider: ~

    Ingenico\Connect\OroCommerce\Entity\Repository\IngenicoSettingsRepository:
        parent: oro_entity.abstract_repository
        arguments:
            - 'Ingenico\Connect\OroCommerce\Entity\IngenicoSettings'
        calls:
            - [setAclHelper, ['@oro_security.acl_helper']]

    ingenico.method.generator.identifier.ingenico:
        parent: oro_integration.generator.prefixed_identifier_generator
        public: true
        arguments:
            - '%ingenico.method.identifier_prefix.ingenico%'

    Ingenico\Connect\OroCommerce\Method\Config\Factory\IngenicoConfigFactory:
        arguments:
            - '@ingenico.method.generator.identifier.ingenico'

    Ingenico\Connect\OroCommerce\Method\Config\Provider\IngenicoConfigProvider:
        arguments:
            - '@doctrine'
            - '@logger'
            - '@Ingenico\Connect\OroCommerce\Method\Config\Factory\IngenicoConfigFactory'

    Ingenico\Connect\OroCommerce\Method\Handler\AbstractPaymentProductHandler:
        abstract: true
        arguments:
            - '@Ingenico\Connect\OroCommerce\Ingenico\Gateway\Gateway'
            - '@Ingenico\Connect\OroCommerce\Normalizer\AmountNormalizer'
            - '@Ingenico\Connect\OroCommerce\Ingenico\Provider\CheckoutInformationProvider'
            - '@logger'

    Ingenico\Connect\OroCommerce\Method\Handler\CreditCardPaymentProductHandler:
        parent: Ingenico\Connect\OroCommerce\Method\Handler\AbstractPaymentProductHandler
        arguments:
            - '@Ingenico\Connect\OroCommerce\Provider\PaymentTransactionProvider'
        tags:
            - { name: ingenico.payment_product.handler }

    Ingenico\Connect\OroCommerce\Method\Handler\AchPaymentProductHandler:
        parent: Ingenico\Connect\OroCommerce\Method\Handler\AbstractPaymentProductHandler
        tags:
            - { name: ingenico.payment_product.handler}

    Ingenico\Connect\OroCommerce\Method\Handler\SepaPaymentProductHandler:
        parent: Ingenico\Connect\OroCommerce\Method\Handler\AbstractPaymentProductHandler
        tags:
            - { name: ingenico.payment_product.handler}

    Ingenico\Connect\OroCommerce\Method\Handler\PaymentProductHandlerRegistry:
        arguments:
            - !tagged_iterator ingenico.payment_product.handler

    Ingenico\Connect\OroCommerce\Provider\PaymentTransactionProvider:
        parent: oro_payment.provider.payment_transaction

    Ingenico\Connect\OroCommerce\Method\Factory\IngenicoPaymentMethodFactory:
        arguments:
            - '@Ingenico\Connect\OroCommerce\Method\Handler\PaymentProductHandlerRegistry'
            - '@Ingenico\Connect\OroCommerce\Ingenico\Gateway\Gateway'

    Ingenico\Connect\OroCommerce\Method\Provider\IngenicoPaymentMethodProvider:
        arguments:
            - '@Ingenico\Connect\OroCommerce\Method\Config\Provider\IngenicoConfigProvider'
            - '@Ingenico\Connect\OroCommerce\Method\Factory\IngenicoPaymentMethodFactory'
        tags:
            - { name: oro_payment.payment_method_provider }

    Ingenico\Connect\OroCommerce\Method\View\Factory\IngenicoViewFactory:
        arguments:
            - '@oro_locale.helper.localization'
            - '@oro_locale.manager.localization'
            - '@security.token_storage'
            - '@Ingenico\Connect\OroCommerce\Normalizer\AmountNormalizer'
            - '@Ingenico\Connect\OroCommerce\Provider\PaymentTransactionProvider'

    Ingenico\Connect\OroCommerce\Method\View\Provider\IngenicoViewProvider:
        arguments:
            - '@Ingenico\Connect\OroCommerce\Method\Config\Provider\IngenicoConfigProvider'
            - '@Ingenico\Connect\OroCommerce\Method\View\Factory\IngenicoViewFactory'
        tags:
            - { name: oro_payment.payment_method_view_provider }

    Ingenico\Connect\OroCommerce\Ingenico\Gateway\Gateway:
        arguments:
            - '@Ingenico\Connect\OroCommerce\Ingenico\Client\Client'
            - '@Ingenico\Connect\OroCommerce\Ingenico\Request\RequestRegistry'
            - '@Ingenico\Connect\OroCommerce\Ingenico\Converter\RequestBodyConverter'
            - '@logger'

    Ingenico\Connect\OroCommerce\Ingenico\Request\RequestRegistry:
        arguments:
            - !tagged_iterator ingenico.ingenico.request

    Ingenico\Connect\OroCommerce\Ingenico\Request\CreateSessionRequest:
        tags:
            - { name: ingenico.ingenico.request }

    Ingenico\Connect\OroCommerce\Ingenico\Request\Payments\CreatePaymentRequest:
        tags:
            - { name: ingenico.ingenico.request }

    Ingenico\Connect\OroCommerce\Ingenico\Request\Payments\CreateCardsPaymentRequest:
        tags:
            - { name: ingenico.ingenico.request }

    Ingenico\Connect\OroCommerce\Ingenico\Request\Payments\DirectDebitPaymentRequest:
        tags:
            - { name: ingenico.ingenico.request }

    Ingenico\Connect\OroCommerce\Ingenico\Request\Payments\CreateSepaDirectDebitPaymentRequest:
        tags:
            - { name: ingenico.ingenico.request }

    Ingenico\Connect\OroCommerce\Ingenico\Request\Payments\CreateSepaDirectDebitPaymentTokenRequest:
        tags:
            - { name: ingenico.ingenico.request }

    Ingenico\Connect\OroCommerce\Ingenico\Request\Payments\ApprovePaymentRequest:
        tags:
            - { name: ingenico.ingenico.request }

    Ingenico\Connect\OroCommerce\Ingenico\Request\Payments\TokenizePaymentRequest:
        tags:
            - { name: ingenico.ingenico.request }

    Ingenico\Connect\OroCommerce\Ingenico\Converter\RequestBodyConverter:
        arguments:
            - '@property_accessor'

    Ingenico\Connect\OroCommerce\Ingenico\Client\Client:
        arguments:
            - '@Ingenico\Connect\OroCommerce\Ingenico\Factory\SDKClientFactory'

    Ingenico\Connect\OroCommerce\Ingenico\Factory\SDKClientFactory: ~

    Ingenico\Connect\OroCommerce\ParamConverter\PaymentMethodParamConverter:
        arguments:
            - '@oro_payment.payment_method.composite_provider'
        tags:
            - { name: request.param_converter, priority: -3, converter: ingenico_payment_method_param_converter }

    Ingenico\Connect\OroCommerce\Controller\Frontend\IngenicoController:
        public: true
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Ingenico\Connect\OroCommerce\Normalizer\AmountNormalizer:
        arguments:
            - '@oro_pricing.rounding.price_rounding_service'

    Ingenico\Connect\OroCommerce\Ingenico\Provider\CheckoutInformationProvider:
        arguments:
            - '@oro_entity.doctrine_helper'

    Ingenico\Connect\OroCommerce\Action\DirectDebitPaymentTransactionMark:
        parent: oro_payment.action.payment_method_action.abstract
        tags:
            - { name: oro_action.action, alias: ingenico_direct_debit_payment_transaction_mark }

    Ingenico\Connect\OroCommerce\Validator\Constraints\NotBlankDirectDebitTextValidator:
        arguments:
            - '@Ingenico\Connect\OroCommerce\Settings\DataProvider\EnabledProductsDataProvider'
        tags:
            - { name: validator.constraint_validator }
