parameters:
    ingenico.method.identifier_prefix.ingenico: 'ingenico'

services:
    ingenico.form.type.settings:
        class: Ingenico\Connect\OroCommerce\Form\Type\IngenicoSettingsType
        arguments:
            - '@translator.default'
            - '@ingenico.settings.data_provider.payment_actions'
            - '@ingenico.settings.data_provider.enabled_products'
        tags:
            - { name: form.type }

    ingenico.integration.channel:
        class: Ingenico\Connect\OroCommerce\Integration\IngenicoChannel
        tags:
            - { name: oro_integration.channel, type: '%ingenico.method.identifier_prefix.ingenico%' }

    ingenico.integration.transport:
        class: Ingenico\Connect\OroCommerce\Integration\IngenicoTransport
        tags:
            - { name: oro_integration.transport, type: '%ingenico.method.identifier_prefix.ingenico%', channel_type: ingenico }

    ingenico.settings.data_provider.payment_actions:
        class: Ingenico\Connect\OroCommerce\Settings\DataProvider\PaymentActionDataProvider

    ingenico.settings.data_provider.enabled_products:
        class: Ingenico\Connect\OroCommerce\Settings\DataProvider\EnabledProductsDataProvider

    ingenico.repository.settings_repository:
        class: Ingenico\Connect\OroCommerce\Entity\Repository\IngenicoSettingsRepository
        parent: oro_entity.abstract_repository
        arguments:
            - 'Ingenico\Connect\OroCommerce\Entity\IngenicoSettings'
        calls:
            - [setAclHelper, ['@oro_security.acl_helper']]

    ingenico.method.generator.identifier.ingenico:
        parent: oro_integration.generator.prefixed_identifier_generator
        public: true
        arguments:
            - '%ingenico.method.identifier_prefix.ingenico%'

    ingenico.method.config.factory.ingenico:
        class: 'Ingenico\Connect\OroCommerce\Method\Config\Factory\IngenicoConfigFactory'
        public: false
        arguments:
            - '@ingenico.method.generator.identifier.ingenico'

    ingenico.method.config.provider.ingenico:
        class: 'Ingenico\Connect\OroCommerce\Method\Config\Provider\IngenicoConfigProvider'
        public: false
        arguments:
            - '@doctrine'
            - '@logger'
            - '@ingenico.method.config.factory.ingenico'

    ingenico.payment_product_group.handler.credit_card:
        class: Ingenico\Connect\OroCommerce\Method\Handler\CreditCardPaymentProductHandler
        public: false
        arguments:
            - '@ingenico.ingenico.gateway'
        tags:
            - { name: ingenico.payment_product_group.handler}

    ingenico.payment_product_group.handlers_registry:
        class: Ingenico\Connect\OroCommerce\Method\Handler\PaymentProductHandlerRegistry
        public: false
        arguments:
            - !tagged_iterator ingenico.payment_product_group.handler

    ingenico.factory.method.ingenico:
        class: 'Ingenico\Connect\OroCommerce\Method\Factory\IngenicoPaymentMethodFactory'
        public: false
        arguments:
            - '@ingenico.payment_product_group.handlers_registry'
            - '@ingenico.ingenico.gateway'

    ingenico.payment_method_provider.ingenico:
        class: 'Ingenico\Connect\OroCommerce\Method\Provider\IngenicoPaymentMethodProvider'
        public: false
        arguments:
            - '@ingenico.method.config.provider.ingenico'
            - '@ingenico.factory.method.ingenico'
        tags:
            - { name: oro_payment.payment_method_provider }

    ingenico.factory.method_view.ingenico:
        class: Ingenico\Connect\OroCommerce\Method\View\Factory\IngenicoViewFactory
        public: false

    ingenico.payment_method_view_provider.ingenico:
        class: Ingenico\Connect\OroCommerce\Method\View\Provider\IngenicoViewProvider
        public: false
        arguments:
            - '@ingenico.method.config.provider.ingenico'
            - '@ingenico.factory.method_view.ingenico'
        tags:
            - { name: oro_payment.payment_method_view_provider }

    ingenico.ingenico.gateway:
        class: Ingenico\Connect\OroCommerce\Ingenico\Gateway\Gateway
        public: false
        arguments:
            - '@ingenico.ingenico.client'
            - '@ingenico.ingenico.request.registry'
            - '@ingenico.ingenico.converter.request'

    ingenico.ingenico.request.registry:
        class: Ingenico\Connect\OroCommerce\Ingenico\Request\RequestRegistry
        public: false
        arguments:
            - !tagged_iterator ingenico.ingenico.request

    ingenico.ingenico.request.create_session:
        class: Ingenico\Connect\OroCommerce\Ingenico\Request\CreateSessionRequest
        public: false
        tags:
            - { name: ingenico.ingenico.request }

    ingenico.ingenico.request.create_payment:
         class: Ingenico\Connect\OroCommerce\Ingenico\Request\CreatePaymentRequest
         public: false
         tags:
             - { name: ingenico.ingenico.request }

    ingenico.ingenico.converter.request:
        class: Ingenico\Connect\OroCommerce\Ingenico\Converter\RequestBodyConverter
        public: false

    ingenico.ingenico.client:
        class: Ingenico\Connect\OroCommerce\Ingenico\Client\Client
        public: false
        arguments:
            - '@ingenico.ingenico.factory.client'

    ingenico.ingenico.factory.client:
        class: Ingenico\Connect\OroCommerce\Ingenico\Factory\ClientFactory
        public: false

    Ingenico\Connect\OroCommerce\Method\Provider\IngenicoPaymentMethodProvider:
        alias: ingenico.payment_method_provider.ingenico
        public: true

    Ingenico\Connect\OroCommerce\Controller\Frontend\IngenicoController:
        public: true
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
