Ingenico\Connect\OroCommerce\Entity\IngenicoSettings:
    properties:
        apiKeyId:
            - NotBlank: ~
            - Length:
                  max: 255
        apiSecret:
            - NotBlank: ~
            - Length:
                  max: 255
        apiEndpoint:
            - NotBlank: ~
        merchantId:
            - NotBlank: ~
            - Length:
                  max: 255
        enabledProducts:
            - NotBlank: ~
        paymentAction:
            - NotBlank: ~

Oro\Bundle\IntegrationBundle\Entity\Channel:
    constraints:
        - Ingenico\Connect\OroCommerce\Validator\Constraints\NotBlankDirectDebitText: ~
