Ingenico\Connect\OroCommerce\Entity\IngenicoSettings:
    properties:
        labels:
            - NotBlank: ~
        shortLabels:
            - NotBlank: ~
        apiKeyId:
            - NotBlank: ~
            - Length:
                  max: 255
        apiSecret:
            - NotBlank: ~
            - Length:
                  max: 255
        apiEndpoint:
            - NotBlank: ~
        merchantId:
            - NotBlank: ~
            - Length:
                  max: 255
        enabledProducts:
            - NotBlank: ~
        paymentAction:
            - NotBlank: ~
        directDebitText:
            - Length:
                  # Max length according to the API
                  # See Ingenico\Connect\OroCommerce\Ingenico\Option\Payment\DirectDebitPayment\DirectDebitText
                  max: 50

Oro\Bundle\IntegrationBundle\Entity\Channel:
    constraints:
        - Ingenico\Connect\OroCommerce\Validator\Constraints\NotBlankDirectDebitText: ~
