map:
    "*":
        underscore: ingenico/js/extend/underscore
    ingenico/js/extend/underscore:
        underscore: underscore
app-modules:
    - ingenico/js/app/modules/template-macros-module
aliases:
    connect-sdk-client-js$: npmassets/connect-sdk-client-js/dist/connectsdk.noEncrypt
dynamic-imports:
    ingenico:
        - ingenico/js/app/stub/connect-sdk-client-mock
        - ingenico/js/app/components/ingenico-payment-component
        - ingenico/js/app/components/ingenico-payment-method-component
        - ingenico/js/validator/sepa-iban
        - ingenico/js/validator/ingenico-error-mapping/not-blank
        - ingenico/js/validator/ingenico-error-mapping/length
        - ingenico/js/validator/ingenico-error-mapping/expiration-date
        - ingenico/js/validator/ingenico-error-mapping/luhn
        - ingenico/js/validator/ingenico-error-mapping/regular-expression
